### ISSUE TITLE
Superflat broken

### ISSUE THREAD

**Issue by ireece1** [Team-RTG/Realistic-Terrain-Generation#1326]
https://paste.dimdev.org/gonihatupu.mccrash

Superflat worlds won't generate at all.

**Comment by srs-bsns** [comment]
```
java.lang.IllegalStateException: Not a JSON Object: 3
    at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
    at rtg.api.world.gen.RTGChunkGenSettings$Serializer.deserialize(RTGChunkGenSettings.java:572)
    at rtg.api.world.gen.RTGChunkGenSettings$Serializer.deserialize(RTGChunkGenSettings.java:560)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at rtg.api.world.gen.RTGChunkGenSettings$Factory.jsonToFactory(RTGChunkGenSettings.java:415)
    at rtg.api.world.RTGWorld.<init>(RTGWorld.java:60)
    at rtg.api.world.RTGWorld.getInstance(RTGWorld.java:79)
    at rtg.world.WorldTypeRTG.getBiomeProvider(WorldTypeRTG.java:51)
    ...
```
You are going to have to provide more info than that, because that stacktrace is clearly showing that the game is starting with the RTG world type (not superflat). This is the only scenerio in which `WorldTypeRTG#getBiomeProvider` would get called.
The JSON parse error is because an erroneous chunk generator setting string is being passed that is not valid JSON.

I can not reproduce this at all.

**Comment by SirChamomile** [comment]
I was having a similar problem? If I go in to create a superflat world, click customize the kind of superflat I would like, and then click done, it has changed back to RTG. There is no way to get it to stay as superflat.

**Comment by srs-bsns** [comment]
Until the next build is released, in `rtg.cfg` set `B:rtgWorldTypeByDefault` to `false`. This will prevent the world type selection reverting back to RTG when exiting the Customize World Screen after configuring another world type, such as FLAT.
