### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException probably due to JEID

### ISSUE THREAD

**Issue by TCreopargh** [Team-RTG/Realistic-Terrain-Generation#1358]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 14.23.5.2847
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
Minecraft crashes upon generating a world with RTG.

The crash report looks like this:

```
java.lang.ArrayIndexOutOfBoundsException: 256
    at rtg.world.biome.BiomeAnalyzer.lambda$initBiomes$0(BiomeAnalyzer.java:77)
    at com.google.common.collect.Maps$KeySet.lambda$forEach$0(Maps.java:3822)
    at com.google.common.collect.HashBiMap$Inverse.lambda$forEach$0(HashBiMap.java:693)
    at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528)
    at com.google.common.collect.HashBiMap$Inverse.forEach(HashBiMap.java:693)
    at com.google.common.collect.Maps$KeySet.forEach(Maps.java:3822)
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
    at rtg.world.biome.BiomeAnalyzer.initBiomes(BiomeAnalyzer.java:61)
    at rtg.world.biome.BiomeAnalyzer.<init>(BiomeAnalyzer.java:35)
    at rtg.world.gen.ChunkGeneratorRTG.<init>(ChunkGeneratorRTG.java:68)
    at rtg.world.WorldTypeRTG.getChunkGenerator(WorldTypeRTG.java:75)
    at net.minecraft.world.WorldProvider.createChunkGenerator(WorldProvider.java:63)
    at net.minecraft.world.WorldServer.createChunkProvider(WorldServer.java:848)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:118)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:132)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```
probably because I installed JEID which added the support for more biome IDs but RTG can't recognize them.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. install RTG and JEID, along with many other mods that adds a lot of biomes (Biomes of Plenty and Traverse for example)
2. generate a world with RTG
3. the game crashes

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

https://gist.github.com/TCreopargh/8e225175e4a97151d09038838358fe36

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1329#issuecomment-542038247
