### ISSUE TITLE
[RTG 0.5.0 snapshot-2] class cast exception with Witchery.

### ISSUE THREAD

**Issue by MrGraphic** [Team-RTG/Realistic-Terrain-Generation#387]
Related to #380 .
Fml log: https://gist.github.com/MrGraphic/7550aca11f6ba7383885
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.biome.WorldChunkManager cannot be cast to rtg.world.biome.WorldChunkManagerRTG
	at rtg.world.gen.ChunkProviderRTG.<init>(ChunkProviderRTG.java:97)
	at rtg.world.WorldTypeRTG.getChunkGenerator(WorldTypeRTG.java:37)
	at com.emoniph.witchery.dimension.WorldProviderDreamWorld.func_76555_c(WorldProviderDreamWorld.java:70)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
	at net.minecraft.world.World.<init>(World.java:245)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by whichonespink44** [comment]
Thanks for reporting.

This should now be fixed in [snapshot 3](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/download/v0.5.0-snapshot-3/RTG-1.7.10-0.5.0-snapshot-3.jar)

**Comment by MrGraphic** [comment]
Yup , it works now. However Witchery's Dream World lost his important aspect - being overworlds reflection. Well, better this than nothing :).
Thanks
