### ISSUE TITLE
0.8 RC-1 Already decorating Streams mod

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Team-RTG/Realistic-Terrain-Generation#684]
fastcraft-1.23.jar monitorBiomeDecorators = true
https://gist.github.com/354375b43fe362e9f48407d2ddd1aa94
and
https://gist.github.com/954593d2588517b9701ddf8703408373
what to do?

and was able to create a map, But then after 10 seconds crash.
https://gist.github.com/e6244a28cf38c1b42c161ca3e7df4532

UP
found the mod which causes crash
Farseek-1.0.11.jar
Streams-0.2.jar
on RTG-1.7.10-0.8.0-snapshot-5.jar all ok

**Comment by whichonespink44** [comment]
A lot of other people have been reporting the 'Already Decorating' crash, so we'll look into this and try to get to the bottom of it.

Might also be related to the 1.23 version of Fastcraft because I haven't gotten this crash when testing RC-1 with Streams.

**Comment by whichonespink44** [comment]
Other people who have posted crash reports:

[CheshireKatt](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2563) - http://pastebin.com/Pu102iYp

[Titus_](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2570) - http://pastebin.com/MKyewZJr (line 514)

**Comment by Zeno410** [comment]
It's an odd error because it happen in a re-entrance of CPRTG.doGenerate(), and the code disallows that. The only thing I can think of is that something has made multiple copies of CPRTG.

**Comment by whichonespink44** [comment]
Could it be the newer versions of Fastcraft? Two of the three crash reports are using Fastcraft 1.2.3 and the other is using 1.2.2

**Comment by MohawkyMagoo** [comment]
Decorating crash when loading game means I cannot get to stage to open a single world - at all, so cannot test this version. Note - using Fastcraft 1.21 still  

RTG-1.7.10-0.8.0-RC-1
Streams-0.2
Farseek-1.0.11
Fastcraft 1.21

Time: 05/05/16 08:21
Description: Exception in server tick loop

java.lang.RuntimeException: Already decorating!!
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at rtg.world.biome.realistic.RealisticBiomeBase.rDecorateSeedBiome(RealisticBiomeBase.java:295)
	at rtg.world.biome.deco.DecoBaseBiomeDecorations.generate(DecoBaseBiomeDecorations.java:93)
	at rtg.world.biome.realistic.RealisticBiomeBase.decorateInAnOrderlyFashion(RealisticBiomeBase.java:601)
	at rtg.world.gen.ChunkProviderRTG.doPopulate(ChunkProviderRTG.java:1053)
	at rtg.world.gen.ChunkProviderRTG.decorateIfOtherwiseSurrounded(ChunkProviderRTG.java:421)
	at rtg.world.gen.ChunkProviderRTG$1.accept(ChunkProviderRTG.java:133)
	at rtg.world.gen.ChunkProviderRTG$1.accept(ChunkProviderRTG.java:123)
	at rtg.event.EventManagerRTG.onChunkLoadEvent(EventManagerRTG.java:272)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_176_EventManagerRTG_onChunkLoadEvent_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:189)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by srs-bsns** [comment]
There's no problem with Fastcraft, this is happening because of Streams.

RTG-1.7.10-0.8.0-RC1
Fastcraft-1.23
Farseek-1.0.11
Streams-0.2
Seed: 6924026457310522769

This will crash on world init.

It will still crash if Fastcraft is removed.
It will stop crashing if Streams is removed.

**Comment by Zeno410** [comment]
My latest pull fixes the crash, although the Streams don't seem to be getting made. I'll have to talk to Delvr about this.

**Comment by whichonespink44** [comment]
Temporary fix added in 7704310 - will try to release another RC tonight so testing can resume whilst we investigate a solution for this.

**Comment by SvEgiiVEteR** [comment]
I will not create a new question... could the problem be in something else.
sometimes if I find a thaumcraft biome in the log like this spam
https://gist.github.com/e74ec8deec8373ba28b4369230adef12
no crash

**Comment by Zeno410** [comment]
The crash has been fixed but Streams don't generate at all in the current release. Delvr and I are working on this and we currently have the Streams generating but not correctly in unreleased test versions. They are done in a two-stage process and the second stage only gets done about half the time, leaving placeholder cobblestone where the Streams are supposed to go.

**Comment by whichonespink44** [comment]
Fixed in 03f95eb
