### ISSUE TITLE
UBC: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#770]
@srs-bsns posted this in Discord, so just posting here for reference.

```
Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException: 2375
    at exterminatorJeff.undergroundBiomes.common.WorldGenManager.cacheUndergroundBiomeGenAt(WorldGenManager.java:200)
    at exterminatorJeff.undergroundBiomes.worldGen.BiomeUndergroundCacheBlock.<init>(BiomeUndergroundCacheBlock.java:29)
    at exterminatorJeff.undergroundBiomes.common.UBiomeCache.getUndergroundBiomeCacheBlock(UBiomeCache.java:32)
    at exterminatorJeff.undergroundBiomes.common.WorldGenManager.chunkBiomeCache(WorldGenManager.java:159)
    at exterminatorJeff.undergroundBiomes.worldGen.UBBlockProvider.strataColumn(UBBlockProvider.java:59)
    at rtg.util.UBColumnCache.column(UBColumnCache.java:27)
    at rtg.world.gen.surface.SurfaceBase.hcCobble(SurfaceBase.java:116)
    at rtg.world.gen.surface.vanilla.SurfaceVanillaSavannaM.paintTerrain(SurfaceVanillaSavannaM.java:46)
    at rtg.world.biome.realistic.RealisticBiomeBase.rReplace(RealisticBiomeBase.java:495)
    at rtg.world.gen.ChunkProviderRTG.replaceBlocksForBiome(ChunkProviderRTG.java:485)
    at rtg.world.gen.ChunkProviderRTG.func_73154_d(ChunkProviderRTG.java:310)
```

I suspect it might have something to do with the recent cobblestone boulders using UBC cobble:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/feature/WorldGenBlob.java#L83-L84

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/util/BoulderUtil.java

Although, having said that... it's hcCobble() in the stack, and not BoulderUtil.

**Comment by srs-bsns** [comment]
I'm not sure there's anymore useful information, but here's the full crash report: http://pastebin.com/8mvFSu9v

And in addition to that, I was able to build a world using UBC without Highlands and with EBXL, however, there were also additional mods present and different config settings, so it's hardly fallowing any kind of scientific method.

**Comment by Zeno410** [comment]
It looks like the problem is sharing the IntCache with other functions. I've been having trouble with multithreading and the IntCache. I'll rewrite the UB function.
